let aiDatabase = [
  {
    category: ENUM_CATEGORY_TYPE.ALL | ENUM_CATEGORY_TYPE.ASSISTANT,
    categoryName: "Assistente",
    name: "Gemini",
    info: "Gemini foi criada pelo Google e treinada com uma enorme quantidade de informação. Gemini é capaz de gerar textos, traduzir idiomas, escrever diferentes tipos de conteúdo criativo e responder suas perguntas de forma informativa e útil.",
    img: "../../resources/images/AIs/Gemini.png",
    link: "https://gemini.google.com/",
    price: "GRATUITO PAGO",
  },
  {
    category: ENUM_CATEGORY_TYPE.ALL | ENUM_CATEGORY_TYPE.ASSISTANT,
    categoryName: "Assistente",
    name: "ChatGPT",
    info: "ChatGPT foi criada pelo OpenAI e treinada com uma enorme quantidade de informação. ChatGPT é capaz de gerar textos, traduzir idiomas, escrever diferentes tipos de conteúdo criativo e responder suas perguntas de forma informativa e útil.",
    img: "../../resources/images/AIs/ChatGPT.png",
    link: "https://chatgpt.com/",
    price: "GRATUITO PAGO",
  },
  {
    category:
      ENUM_CATEGORY_TYPE.ALL |
      ENUM_CATEGORY_TYPE.ASSISTANT |
      ENUM_CATEGORY_TYPE.ARTIST,
    categoryName: "Assistente / Artista",
    name: "Microsoft Copilot",
    info: "Microsoft Copilot foi criada pelo Microsoft. Copilot é capaz de ajudar com tarefas, responder perguntas, gerar textos, traduzir idiomas e gerar imagens usando DALL·E.",
    img: "../../resources/images/AIs/WindowsCopilot.png",
    link: "https://support.microsoft.com/pt-br/windows/bem-vindo-ao-copilot-no-windows-675708af-8c16-4675-afeb-85a5a476ccb0",
    price: "GRATUITO",
  },
  {
    category: ENUM_CATEGORY_TYPE.ALL | ENUM_CATEGORY_TYPE.COPILOT,
    categoryName: "Copiloto",
    name: "GitHub Copilot",
    info: "O GitHub Copilot é uma ferramenta de IA desenvolvida pela GitHub e OpenAI que atua como um assistente de codificação, oferecendo sugestões de código, funções e blocos inteiros com base no contexto enquanto você escreve no editor, como o Visual Studio Code.",
    img: "../../resources/images/AIs/GitHubCopilot.png",
    link: "https://github.com/features/copilot",
    price: "PAGO",
  },
  {
    category: ENUM_CATEGORY_TYPE.ALL | ENUM_CATEGORY_TYPE.SYNTHESIZER,
    categoryName: "Sintetizador",
    name: "TTSOpenAI",
    info: "O TTSOpenAI é uma IA que converte texto em voz de forma natural e clara, utilizando tecnologia avançada para criar áudios realistas para diversas aplicações.",
    img: "../../resources/images/AIs/TTSOpenAI.png",
    link: "https://ttsopenai.com/",
    price: "GRATUITO PAGO",
  },
  {
    category: ENUM_CATEGORY_TYPE.ALL | ENUM_CATEGORY_TYPE.ARTIST,
    categoryName: "Artista",
    name: "DALL·E",
    info: "O DALL·E é uma IA da OpenAI que cria imagens a partir de descrições textuais, gerando visuais detalhados e criativos com base em comandos escritos.",
    img: "../../resources/images/AIs/ChatGPT.png",
    link: "https://openai.com/index/dall-e-2/",
    price: "GRATUITO PAGO",
  },
  {
    category: ENUM_CATEGORY_TYPE.ALL | ENUM_CATEGORY_TYPE.COPILOT,
    categoryName: "Copiloto",
    name: "Codeium",
    info: "O Codeium é uma IA que auxilia desenvolvedores, integrando-se a editores de código e IDEs para fornecer sugestões automáticas e completar trechos de código, aumentando a eficiência na programação.",
    img: "../../resources/images/AIs/Codeium.png",
    link: "https://codeium.com/",
    price: "GRATUITO",
  },
  {
    category: ENUM_CATEGORY_TYPE.ALL | ENUM_CATEGORY_TYPE.ARTIST,
    categoryName: "Artista",
    name: "SeaArt",
    info: "A SeaArt é uma IA que gera imagens e arte digital a partir de descrições textuais, permitindo criar visuais detalhados e criativos com base em ideias e conceitos.",
    img: "../../resources/images/AIs/SeaArt.png",
    link: "https://www.seaart.ai/",
    price: "GRATUITO PAGO",
  },
];
